version: "2"
services:
  redis:
    image: redislabs/redisearch:2.2.1
    ports:
      - "6379:6379"

  backend:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - /var/lib/flatpak
      - .:/app
